package com.web.hospital.model;

import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

import java.sql.Time;
import java.time.LocalTime;
import java.util.Date;

public class booking {

    private Integer stt;

    private String hotenbenhnhan;

    private String namsinh;

    private String gioitinh;

    private String sdt;

    private String diachi;

    private String email;

    private String hotenbacsi;

    private String ngaydat;

    private String loinhan;
    
    private String gia;
    private int idd;
    private int mount;

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Temporal(TemporalType.DATE)
    private Date day;
    private int id;
    private int idphong;
    private String diachiPhong;
    private LocalTime thoigiandat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Booking.Stt
     *
     * @return the value of dbo.Booking.Stt
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public Integer getStt() {
        return stt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Booking.Stt
     *
     * @param stt the value for dbo.Booking.Stt
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public void setStt(Integer stt) {
        this.stt = stt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Booking.hoTenBenhNhan
     *
     * @return the value of dbo.Booking.hoTenBenhNhan
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public String getHotenbenhnhan() {
        return hotenbenhnhan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Booking.hoTenBenhNhan
     *
     * @param hotenbenhnhan the value for dbo.Booking.hoTenBenhNhan
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public void setHotenbenhnhan(String hotenbenhnhan) {
        this.hotenbenhnhan = hotenbenhnhan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Booking.namSinh
     *
     * @return the value of dbo.Booking.namSinh
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public String getNamsinh() {
        return namsinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Booking.namSinh
     *
     * @param namsinh the value for dbo.Booking.namSinh
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public void setNamsinh(String namsinh) {
        this.namsinh = namsinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Booking.gioiTinh
     *
     * @return the value of dbo.Booking.gioiTinh
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public String getGioitinh() {
        return gioitinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Booking.gioiTinh
     *
     * @param gioitinh the value for dbo.Booking.gioiTinh
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Booking.SDT
     *
     * @return the value of dbo.Booking.SDT
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public String getSdt() {
        return sdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Booking.SDT
     *
     * @param sdt the value for dbo.Booking.SDT
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Booking.diaChi
     *
     * @return the value of dbo.Booking.diaChi
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public String getDiachi() {
        return diachi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Booking.diaChi
     *
     * @param diachi the value for dbo.Booking.diaChi
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Booking.email
     *
     * @return the value of dbo.Booking.email
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Booking.email
     *
     * @param email the value for dbo.Booking.email
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Booking.hoTenBacSi
     *
     * @return the value of dbo.Booking.hoTenBacSi
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public String getHotenbacsi() {
        return hotenbacsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Booking.hoTenBacSi
     *
     * @param hotenbacsi the value for dbo.Booking.hoTenBacSi
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public void setHotenbacsi(String hotenbacsi) {
        this.hotenbacsi = hotenbacsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Booking.ngaydat
     *
     * @return the value of dbo.Booking.ngaydat
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public String getNgaydat() {
        return ngaydat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Booking.ngaydat
     *
     * @param ngaydat the value for dbo.Booking.ngaydat
     *
     * @mbg.generated Thu May 09 14:06:43 ICT 2024
     */
    public void setNgaydat(String ngaydat) {
        this.ngaydat = ngaydat;
    }

 

	public String getLoinhan() {
		return loinhan;
	}

	public void setLoinhan(String loinhan) {
		this.loinhan = loinhan;
	}

	public int getIdd() {
		return idd;
	}

	public void setIdd(int idd) {
		this.idd = idd;
	}

	public String getGia() {
		return gia;
	}

	public void setGia(String gia) {
		this.gia = gia;
	}

    public int getMount() {
        return mount;
    }

    public void setMount(int mount) {
        this.mount = mount;
    }

    public Date getDay() {
        return day;
    }

    public void setDay(Date day) {
        this.day = day;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIdphong() {
        return idphong;
    }

    public void setIdphong(int idphong) {
        this.idphong = idphong;
    }

    public String getDiachiPhong() {
        return diachiPhong;
    }

    public void setDiachiPhong(String diachiPhong) {
        this.diachiPhong = diachiPhong;
    }

    public LocalTime getThoigiandat() {
        return thoigiandat;
    }

    public void setThoigiandat(LocalTime thoigiandat) {
        this.thoigiandat = thoigiandat;
    }
}