package com.web.hospital.model;

public class doctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Doctor.idD
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    private Integer idd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Doctor.hoTenBacSi
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    private String hotenbacsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Doctor.namSinh
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    private String namsinh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Doctor.gioiTinh
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    private String gioitinh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Doctor.SDT
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    private String sdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Doctor.email
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Doctor.maKhoa
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    private Integer makhoa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Doctor.role
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Doctor.loiNhan
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    private String loinhan;
    
    private String hinhanh;

    private String tenKhoa;
    
    private String gia;
    
    private String username;
    private int mount;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Doctor.idD
     *
     * @return the value of dbo.Doctor.idD
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public Integer getIdd() {
        return idd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Doctor.idD
     *
     * @param idd the value for dbo.Doctor.idD
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public void setIdd(Integer idd) {
        this.idd = idd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Doctor.hoTenBacSi
     *
     * @return the value of dbo.Doctor.hoTenBacSi
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public String getHotenbacsi() {
        return hotenbacsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Doctor.hoTenBacSi
     *
     * @param hotenbacsi the value for dbo.Doctor.hoTenBacSi
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public void setHotenbacsi(String hotenbacsi) {
        this.hotenbacsi = hotenbacsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Doctor.namSinh
     *
     * @return the value of dbo.Doctor.namSinh
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public String getNamsinh() {
        return namsinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Doctor.namSinh
     *
     * @param namsinh the value for dbo.Doctor.namSinh
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public void setNamsinh(String namsinh) {
        this.namsinh = namsinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Doctor.gioiTinh
     *
     * @return the value of dbo.Doctor.gioiTinh
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public String getGioitinh() {
        return gioitinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Doctor.gioiTinh
     *
     * @param gioitinh the value for dbo.Doctor.gioiTinh
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Doctor.SDT
     *
     * @return the value of dbo.Doctor.SDT
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public String getSdt() {
        return sdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Doctor.SDT
     *
     * @param sdt the value for dbo.Doctor.SDT
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Doctor.email
     *
     * @return the value of dbo.Doctor.email
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Doctor.email
     *
     * @param email the value for dbo.Doctor.email
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Doctor.maKhoa
     *
     * @return the value of dbo.Doctor.maKhoa
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public Integer getMakhoa() {
        return makhoa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Doctor.maKhoa
     *
     * @param makhoa the value for dbo.Doctor.maKhoa
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public void setMakhoa(Integer makhoa) {
        this.makhoa = makhoa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Doctor.role
     *
     * @return the value of dbo.Doctor.role
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Doctor.role
     *
     * @param role the value for dbo.Doctor.role
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Doctor.loiNhan
     *
     * @return the value of dbo.Doctor.loiNhan
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public String getLoinhan() {
        return loinhan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Doctor.loiNhan
     *
     * @param loinhan the value for dbo.Doctor.loiNhan
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    public void setLoinhan(String loinhan) {
        this.loinhan = loinhan;
    }

	public String getHinhanh() {
		return hinhanh;
	}

	public void setHinhanh(String hinhanh) {
		this.hinhanh = hinhanh;
	}

	public String getTenKhoa() {
		return tenKhoa;
	}

	public void setTenKhoa(String tenKhoa) {
		this.tenKhoa = tenKhoa;
	}

	public String getGia() {
		return gia;
	}

	public void setGia(String gia) {
		this.gia = gia;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

    public int getMount() {
        return mount;
    }

    public void setMount(int mount) {
        this.mount = mount;
    }
}