package com.web.hospital.model;

import java.util.Date;

public class historygiaodich {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historygiaodich.idgiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    private Integer idgiaodich;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historygiaodich.magiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    private String magiaodich;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historygiaodich.ngaygiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    private Date ngaygiaodich;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historygiaodich.mount
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    private Integer mount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historygiaodich.id
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historygiaodich.idgiaodich
     *
     * @return the value of dbo.historygiaodich.idgiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    public Integer getIdgiaodich() {
        return idgiaodich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historygiaodich.idgiaodich
     *
     * @param idgiaodich the value for dbo.historygiaodich.idgiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    public void setIdgiaodich(Integer idgiaodich) {
        this.idgiaodich = idgiaodich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historygiaodich.magiaodich
     *
     * @return the value of dbo.historygiaodich.magiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    public String getMagiaodich() {
        return magiaodich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historygiaodich.magiaodich
     *
     * @param magiaodich the value for dbo.historygiaodich.magiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    public void setMagiaodich(String magiaodich) {
        this.magiaodich = magiaodich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historygiaodich.ngaygiaodich
     *
     * @return the value of dbo.historygiaodich.ngaygiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    public Date getNgaygiaodich() {
        return ngaygiaodich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historygiaodich.ngaygiaodich
     *
     * @param ngaygiaodich the value for dbo.historygiaodich.ngaygiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    public void setNgaygiaodich(Date ngaygiaodich) {
        this.ngaygiaodich = ngaygiaodich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historygiaodich.mount
     *
     * @return the value of dbo.historygiaodich.mount
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    public Integer getMount() {
        return mount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historygiaodich.mount
     *
     * @param mount the value for dbo.historygiaodich.mount
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    public void setMount(Integer mount) {
        this.mount = mount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historygiaodich.id
     *
     * @return the value of dbo.historygiaodich.id
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historygiaodich.id
     *
     * @param id the value for dbo.historygiaodich.id
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }
}