package com.web.hospital.model;

import java.util.Date;

public class historylichkham {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historylichkham.Stt
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    private Integer stt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historylichkham.hoTenBenhNhan
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    private String hotenbenhnhan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historylichkham.namSinh
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    private String namsinh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historylichkham.gioiTinh
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    private String gioitinh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historylichkham.SDT
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    private String sdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historylichkham.diaChi
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    private String diachi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historylichkham.email
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historylichkham.hoTenBacSi
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    private String hotenbacsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historylichkham.day
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    private Date day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historylichkham.note
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historylichkham.mount
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    private Integer mount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.historylichkham.id
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    private Integer id;

    private String trangthai;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historylichkham.Stt
     *
     * @return the value of dbo.historylichkham.Stt
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public Integer getStt() {
        return stt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historylichkham.Stt
     *
     * @param stt the value for dbo.historylichkham.Stt
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public void setStt(Integer stt) {
        this.stt = stt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historylichkham.hoTenBenhNhan
     *
     * @return the value of dbo.historylichkham.hoTenBenhNhan
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public String getHotenbenhnhan() {
        return hotenbenhnhan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historylichkham.hoTenBenhNhan
     *
     * @param hotenbenhnhan the value for dbo.historylichkham.hoTenBenhNhan
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public void setHotenbenhnhan(String hotenbenhnhan) {
        this.hotenbenhnhan = hotenbenhnhan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historylichkham.namSinh
     *
     * @return the value of dbo.historylichkham.namSinh
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public String getNamsinh() {
        return namsinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historylichkham.namSinh
     *
     * @param namsinh the value for dbo.historylichkham.namSinh
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public void setNamsinh(String namsinh) {
        this.namsinh = namsinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historylichkham.gioiTinh
     *
     * @return the value of dbo.historylichkham.gioiTinh
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public String getGioitinh() {
        return gioitinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historylichkham.gioiTinh
     *
     * @param gioitinh the value for dbo.historylichkham.gioiTinh
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historylichkham.SDT
     *
     * @return the value of dbo.historylichkham.SDT
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public String getSdt() {
        return sdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historylichkham.SDT
     *
     * @param sdt the value for dbo.historylichkham.SDT
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historylichkham.diaChi
     *
     * @return the value of dbo.historylichkham.diaChi
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public String getDiachi() {
        return diachi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historylichkham.diaChi
     *
     * @param diachi the value for dbo.historylichkham.diaChi
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historylichkham.email
     *
     * @return the value of dbo.historylichkham.email
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historylichkham.email
     *
     * @param email the value for dbo.historylichkham.email
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historylichkham.hoTenBacSi
     *
     * @return the value of dbo.historylichkham.hoTenBacSi
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public String getHotenbacsi() {
        return hotenbacsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historylichkham.hoTenBacSi
     *
     * @param hotenbacsi the value for dbo.historylichkham.hoTenBacSi
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public void setHotenbacsi(String hotenbacsi) {
        this.hotenbacsi = hotenbacsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historylichkham.day
     *
     * @return the value of dbo.historylichkham.day
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historylichkham.day
     *
     * @param day the value for dbo.historylichkham.day
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historylichkham.note
     *
     * @return the value of dbo.historylichkham.note
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historylichkham.note
     *
     * @param note the value for dbo.historylichkham.note
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historylichkham.mount
     *
     * @return the value of dbo.historylichkham.mount
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public Integer getMount() {
        return mount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historylichkham.mount
     *
     * @param mount the value for dbo.historylichkham.mount
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public void setMount(Integer mount) {
        this.mount = mount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.historylichkham.id
     *
     * @return the value of dbo.historylichkham.id
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.historylichkham.id
     *
     * @param id the value for dbo.historylichkham.id
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public String getTrangthai() {
        return trangthai;
    }

    public void setTrangthai(String trangthai) {
        this.trangthai = trangthai;
    }
}