package com.web.hospital.model;

import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;


public class hoso {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.HoSo.idHoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    private Integer idhoso;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.HoSo.hotenbenhnhan
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    private Integer stt;

    private String hotenbenhnhan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.HoSo.namSinh
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    private String namsinh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.HoSo.gioiTinh
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    private String gioitinh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.HoSo.SDT
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    private String sdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.HoSo.diaChi
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    private String diachi;

    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.HoSo.ngayKham
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Temporal(TemporalType.DATE)
    private Date day;

    private LocalDate ngaykham;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.HoSo.idD
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    private Integer idd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.HoSo.hotenbacsi
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    private String hotenbacsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.HoSo.chuanDoan
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    private String chuandoan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.HoSo.donThuoc
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    private String donthuoc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.HoSo.idHoSo
     *
     * @return the value of dbo.HoSo.idHoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public Integer getIdhoso() {
        return idhoso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.HoSo.idHoSo
     *
     * @param idhoso the value for dbo.HoSo.idHoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public void setIdhoso(Integer idhoso) {
        this.idhoso = idhoso;
    }

    public Integer getStt() {
        return stt;
    }

    public void setStt(Integer stt) {
        this.stt = stt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.HoSo.hotenbenhnhan
     *
     * @return the value of dbo.HoSo.hotenbenhnhan
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */



    public String getHotenbenhnhan() {
        return hotenbenhnhan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.HoSo.hotenbenhnhan
     *
     * @param hotenbenhnhan the value for dbo.HoSo.hotenbenhnhan
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public void setHotenbenhnhan(String hotenbenhnhan) {
        this.hotenbenhnhan = hotenbenhnhan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.HoSo.namSinh
     *
     * @return the value of dbo.HoSo.namSinh
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public String getNamsinh() {
        return namsinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.HoSo.namSinh
     *
     * @param namsinh the value for dbo.HoSo.namSinh
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public void setNamsinh(String namsinh) {
        this.namsinh = namsinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.HoSo.gioiTinh
     *
     * @return the value of dbo.HoSo.gioiTinh
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public String getGioitinh() {
        return gioitinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.HoSo.gioiTinh
     *
     * @param gioitinh the value for dbo.HoSo.gioiTinh
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.HoSo.SDT
     *
     * @return the value of dbo.HoSo.SDT
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public String getSdt() {
        return sdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.HoSo.SDT
     *
     * @param sdt the value for dbo.HoSo.SDT
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.HoSo.diaChi
     *
     * @return the value of dbo.HoSo.diaChi
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public String getDiachi() {
        return diachi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.HoSo.diaChi
     *
     * @param diachi the value for dbo.HoSo.diaChi
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.HoSo.ngayKham
     *
     * @return the value of dbo.HoSo.ngayKham
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public Date getDay() {
        return day;
    }

    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.HoSo.idD
     *
     * @return the value of dbo.HoSo.idD
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public Integer getIdd() {
        return idd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.HoSo.idD
     *
     * @param idd the value for dbo.HoSo.idD
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public void setIdd(Integer idd) {
        this.idd = idd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.HoSo.hotenbacsi
     *
     * @return the value of dbo.HoSo.hotenbacsi
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public String getHotenbacsi() {
        return hotenbacsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.HoSo.hotenbacsi
     *
     * @param hotenbacsi the value for dbo.HoSo.hotenbacsi
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public void setHotenbacsi(String hotenbacsi) {
        this.hotenbacsi = hotenbacsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.HoSo.chuanDoan
     *
     * @return the value of dbo.HoSo.chuanDoan
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public String getChuandoan() {
        return chuandoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.HoSo.chuanDoan
     *
     * @param chuandoan the value for dbo.HoSo.chuanDoan
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public void setChuandoan(String chuandoan) {
        this.chuandoan = chuandoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.HoSo.donThuoc
     *
     * @return the value of dbo.HoSo.donThuoc
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public String getDonthuoc() {
        return donthuoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.HoSo.donThuoc
     *
     * @param donthuoc the value for dbo.HoSo.donThuoc
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public void setDonthuoc(String donthuoc) {
        this.donthuoc = donthuoc;
    }


    public LocalDate getNgaykham() {
        return ngaykham;
    }

    public void setNgaykham(LocalDate ngaykham) {
        this.ngaykham = ngaykham;
    }

    public String getFormattedDay() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return ngaykham.format(formatter);
    }
}