package com.web.hospital.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class hosoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public hosoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdhosoIsNull() {
            addCriterion("idHoSo is null");
            return (Criteria) this;
        }

        public Criteria andIdhosoIsNotNull() {
            addCriterion("idHoSo is not null");
            return (Criteria) this;
        }

        public Criteria andIdhosoEqualTo(Integer value) {
            addCriterion("idHoSo =", value, "idhoso");
            return (Criteria) this;
        }

        public Criteria andIdhosoNotEqualTo(Integer value) {
            addCriterion("idHoSo <>", value, "idhoso");
            return (Criteria) this;
        }

        public Criteria andIdhosoGreaterThan(Integer value) {
            addCriterion("idHoSo >", value, "idhoso");
            return (Criteria) this;
        }

        public Criteria andIdhosoGreaterThanOrEqualTo(Integer value) {
            addCriterion("idHoSo >=", value, "idhoso");
            return (Criteria) this;
        }

        public Criteria andIdhosoLessThan(Integer value) {
            addCriterion("idHoSo <", value, "idhoso");
            return (Criteria) this;
        }

        public Criteria andIdhosoLessThanOrEqualTo(Integer value) {
            addCriterion("idHoSo <=", value, "idhoso");
            return (Criteria) this;
        }

        public Criteria andIdhosoIn(List<Integer> values) {
            addCriterion("idHoSo in", values, "idhoso");
            return (Criteria) this;
        }

        public Criteria andIdhosoNotIn(List<Integer> values) {
            addCriterion("idHoSo not in", values, "idhoso");
            return (Criteria) this;
        }

        public Criteria andIdhosoBetween(Integer value1, Integer value2) {
            addCriterion("idHoSo between", value1, value2, "idhoso");
            return (Criteria) this;
        }

        public Criteria andIdhosoNotBetween(Integer value1, Integer value2) {
            addCriterion("idHoSo not between", value1, value2, "idhoso");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanIsNull() {
            addCriterion("hotenbenhnhan is null");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanIsNotNull() {
            addCriterion("hotenbenhnhan is not null");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanEqualTo(String value) {
            addCriterion("hotenbenhnhan =", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanNotEqualTo(String value) {
            addCriterion("hotenbenhnhan <>", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanGreaterThan(String value) {
            addCriterion("hotenbenhnhan >", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanGreaterThanOrEqualTo(String value) {
            addCriterion("hotenbenhnhan >=", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanLessThan(String value) {
            addCriterion("hotenbenhnhan <", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanLessThanOrEqualTo(String value) {
            addCriterion("hotenbenhnhan <=", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanLike(String value) {
            addCriterion("hotenbenhnhan like", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanNotLike(String value) {
            addCriterion("hotenbenhnhan not like", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanIn(List<String> values) {
            addCriterion("hotenbenhnhan in", values, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanNotIn(List<String> values) {
            addCriterion("hotenbenhnhan not in", values, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanBetween(String value1, String value2) {
            addCriterion("hotenbenhnhan between", value1, value2, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanNotBetween(String value1, String value2) {
            addCriterion("hotenbenhnhan not between", value1, value2, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andNamsinhIsNull() {
            addCriterion("namSinh is null");
            return (Criteria) this;
        }

        public Criteria andNamsinhIsNotNull() {
            addCriterion("namSinh is not null");
            return (Criteria) this;
        }

        public Criteria andNamsinhEqualTo(String value) {
            addCriterion("namSinh =", value, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhNotEqualTo(String value) {
            addCriterion("namSinh <>", value, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhGreaterThan(String value) {
            addCriterion("namSinh >", value, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhGreaterThanOrEqualTo(String value) {
            addCriterion("namSinh >=", value, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhLessThan(String value) {
            addCriterion("namSinh <", value, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhLessThanOrEqualTo(String value) {
            addCriterion("namSinh <=", value, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhLike(String value) {
            addCriterion("namSinh like", value, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhNotLike(String value) {
            addCriterion("namSinh not like", value, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhIn(List<String> values) {
            addCriterion("namSinh in", values, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhNotIn(List<String> values) {
            addCriterion("namSinh not in", values, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhBetween(String value1, String value2) {
            addCriterion("namSinh between", value1, value2, "namsinh");
            return (Criteria) this;
        }

        public Criteria andNamsinhNotBetween(String value1, String value2) {
            addCriterion("namSinh not between", value1, value2, "namsinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhIsNull() {
            addCriterion("gioiTinh is null");
            return (Criteria) this;
        }

        public Criteria andGioitinhIsNotNull() {
            addCriterion("gioiTinh is not null");
            return (Criteria) this;
        }

        public Criteria andGioitinhEqualTo(String value) {
            addCriterion("gioiTinh =", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhNotEqualTo(String value) {
            addCriterion("gioiTinh <>", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhGreaterThan(String value) {
            addCriterion("gioiTinh >", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhGreaterThanOrEqualTo(String value) {
            addCriterion("gioiTinh >=", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhLessThan(String value) {
            addCriterion("gioiTinh <", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhLessThanOrEqualTo(String value) {
            addCriterion("gioiTinh <=", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhLike(String value) {
            addCriterion("gioiTinh like", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhNotLike(String value) {
            addCriterion("gioiTinh not like", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhIn(List<String> values) {
            addCriterion("gioiTinh in", values, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhNotIn(List<String> values) {
            addCriterion("gioiTinh not in", values, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhBetween(String value1, String value2) {
            addCriterion("gioiTinh between", value1, value2, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhNotBetween(String value1, String value2) {
            addCriterion("gioiTinh not between", value1, value2, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andSdtIsNull() {
            addCriterion("SDT is null");
            return (Criteria) this;
        }

        public Criteria andSdtIsNotNull() {
            addCriterion("SDT is not null");
            return (Criteria) this;
        }

        public Criteria andSdtEqualTo(String value) {
            addCriterion("SDT =", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtNotEqualTo(String value) {
            addCriterion("SDT <>", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtGreaterThan(String value) {
            addCriterion("SDT >", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtGreaterThanOrEqualTo(String value) {
            addCriterion("SDT >=", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtLessThan(String value) {
            addCriterion("SDT <", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtLessThanOrEqualTo(String value) {
            addCriterion("SDT <=", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtLike(String value) {
            addCriterion("SDT like", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtNotLike(String value) {
            addCriterion("SDT not like", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtIn(List<String> values) {
            addCriterion("SDT in", values, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtNotIn(List<String> values) {
            addCriterion("SDT not in", values, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtBetween(String value1, String value2) {
            addCriterion("SDT between", value1, value2, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtNotBetween(String value1, String value2) {
            addCriterion("SDT not between", value1, value2, "sdt");
            return (Criteria) this;
        }

        public Criteria andDiachiIsNull() {
            addCriterion("diaChi is null");
            return (Criteria) this;
        }

        public Criteria andDiachiIsNotNull() {
            addCriterion("diaChi is not null");
            return (Criteria) this;
        }

        public Criteria andDiachiEqualTo(String value) {
            addCriterion("diaChi =", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotEqualTo(String value) {
            addCriterion("diaChi <>", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiGreaterThan(String value) {
            addCriterion("diaChi >", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiGreaterThanOrEqualTo(String value) {
            addCriterion("diaChi >=", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiLessThan(String value) {
            addCriterion("diaChi <", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiLessThanOrEqualTo(String value) {
            addCriterion("diaChi <=", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiLike(String value) {
            addCriterion("diaChi like", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotLike(String value) {
            addCriterion("diaChi not like", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiIn(List<String> values) {
            addCriterion("diaChi in", values, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotIn(List<String> values) {
            addCriterion("diaChi not in", values, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiBetween(String value1, String value2) {
            addCriterion("diaChi between", value1, value2, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotBetween(String value1, String value2) {
            addCriterion("diaChi not between", value1, value2, "diachi");
            return (Criteria) this;
        }

        public Criteria andNgaykhamIsNull() {
            addCriterion("ngayKham is null");
            return (Criteria) this;
        }

        public Criteria andNgaykhamIsNotNull() {
            addCriterion("ngayKham is not null");
            return (Criteria) this;
        }

        public Criteria andNgaykhamEqualTo(Date value) {
            addCriterionForJDBCDate("ngayKham =", value, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamNotEqualTo(Date value) {
            addCriterionForJDBCDate("ngayKham <>", value, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamGreaterThan(Date value) {
            addCriterionForJDBCDate("ngayKham >", value, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ngayKham >=", value, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamLessThan(Date value) {
            addCriterionForJDBCDate("ngayKham <", value, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ngayKham <=", value, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamIn(List<Date> values) {
            addCriterionForJDBCDate("ngayKham in", values, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamNotIn(List<Date> values) {
            addCriterionForJDBCDate("ngayKham not in", values, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ngayKham between", value1, value2, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ngayKham not between", value1, value2, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andIddIsNull() {
            addCriterion("idD is null");
            return (Criteria) this;
        }

        public Criteria andIddIsNotNull() {
            addCriterion("idD is not null");
            return (Criteria) this;
        }

        public Criteria andIddEqualTo(Integer value) {
            addCriterion("idD =", value, "idd");
            return (Criteria) this;
        }

        public Criteria andIddNotEqualTo(Integer value) {
            addCriterion("idD <>", value, "idd");
            return (Criteria) this;
        }

        public Criteria andIddGreaterThan(Integer value) {
            addCriterion("idD >", value, "idd");
            return (Criteria) this;
        }

        public Criteria andIddGreaterThanOrEqualTo(Integer value) {
            addCriterion("idD >=", value, "idd");
            return (Criteria) this;
        }

        public Criteria andIddLessThan(Integer value) {
            addCriterion("idD <", value, "idd");
            return (Criteria) this;
        }

        public Criteria andIddLessThanOrEqualTo(Integer value) {
            addCriterion("idD <=", value, "idd");
            return (Criteria) this;
        }

        public Criteria andIddIn(List<Integer> values) {
            addCriterion("idD in", values, "idd");
            return (Criteria) this;
        }

        public Criteria andIddNotIn(List<Integer> values) {
            addCriterion("idD not in", values, "idd");
            return (Criteria) this;
        }

        public Criteria andIddBetween(Integer value1, Integer value2) {
            addCriterion("idD between", value1, value2, "idd");
            return (Criteria) this;
        }

        public Criteria andIddNotBetween(Integer value1, Integer value2) {
            addCriterion("idD not between", value1, value2, "idd");
            return (Criteria) this;
        }

        public Criteria andHotenbacsiIsNull() {
            addCriterion("hotenbacsi is null");
            return (Criteria) this;
        }

        public Criteria andHotenbacsiIsNotNull() {
            addCriterion("hotenbacsi is not null");
            return (Criteria) this;
        }

        public Criteria andHotenbacsiEqualTo(String value) {
            addCriterion("hotenbacsi =", value, "hotenbacsi");
            return (Criteria) this;
        }

        public Criteria andHotenbacsiNotEqualTo(String value) {
            addCriterion("hotenbacsi <>", value, "hotenbacsi");
            return (Criteria) this;
        }

        public Criteria andHotenbacsiGreaterThan(String value) {
            addCriterion("hotenbacsi >", value, "hotenbacsi");
            return (Criteria) this;
        }

        public Criteria andHotenbacsiGreaterThanOrEqualTo(String value) {
            addCriterion("hotenbacsi >=", value, "hotenbacsi");
            return (Criteria) this;
        }

        public Criteria andHotenbacsiLessThan(String value) {
            addCriterion("hotenbacsi <", value, "hotenbacsi");
            return (Criteria) this;
        }

        public Criteria andHotenbacsiLessThanOrEqualTo(String value) {
            addCriterion("hotenbacsi <=", value, "hotenbacsi");
            return (Criteria) this;
        }

        public Criteria andHotenbacsiLike(String value) {
            addCriterion("hotenbacsi like", value, "hotenbacsi");
            return (Criteria) this;
        }

        public Criteria andHotenbacsiNotLike(String value) {
            addCriterion("hotenbacsi not like", value, "hotenbacsi");
            return (Criteria) this;
        }

        public Criteria andHotenbacsiIn(List<String> values) {
            addCriterion("hotenbacsi in", values, "hotenbacsi");
            return (Criteria) this;
        }

        public Criteria andHotenbacsiNotIn(List<String> values) {
            addCriterion("hotenbacsi not in", values, "hotenbacsi");
            return (Criteria) this;
        }

        public Criteria andHotenbacsiBetween(String value1, String value2) {
            addCriterion("hotenbacsi between", value1, value2, "hotenbacsi");
            return (Criteria) this;
        }

        public Criteria andHotenbacsiNotBetween(String value1, String value2) {
            addCriterion("hotenbacsi not between", value1, value2, "hotenbacsi");
            return (Criteria) this;
        }

        public Criteria andChuandoanIsNull() {
            addCriterion("chuanDoan is null");
            return (Criteria) this;
        }

        public Criteria andChuandoanIsNotNull() {
            addCriterion("chuanDoan is not null");
            return (Criteria) this;
        }

        public Criteria andChuandoanEqualTo(String value) {
            addCriterion("chuanDoan =", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanNotEqualTo(String value) {
            addCriterion("chuanDoan <>", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanGreaterThan(String value) {
            addCriterion("chuanDoan >", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanGreaterThanOrEqualTo(String value) {
            addCriterion("chuanDoan >=", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanLessThan(String value) {
            addCriterion("chuanDoan <", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanLessThanOrEqualTo(String value) {
            addCriterion("chuanDoan <=", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanLike(String value) {
            addCriterion("chuanDoan like", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanNotLike(String value) {
            addCriterion("chuanDoan not like", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanIn(List<String> values) {
            addCriterion("chuanDoan in", values, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanNotIn(List<String> values) {
            addCriterion("chuanDoan not in", values, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanBetween(String value1, String value2) {
            addCriterion("chuanDoan between", value1, value2, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanNotBetween(String value1, String value2) {
            addCriterion("chuanDoan not between", value1, value2, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andDonthuocIsNull() {
            addCriterion("donThuoc is null");
            return (Criteria) this;
        }

        public Criteria andDonthuocIsNotNull() {
            addCriterion("donThuoc is not null");
            return (Criteria) this;
        }

        public Criteria andDonthuocEqualTo(String value) {
            addCriterion("donThuoc =", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocNotEqualTo(String value) {
            addCriterion("donThuoc <>", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocGreaterThan(String value) {
            addCriterion("donThuoc >", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocGreaterThanOrEqualTo(String value) {
            addCriterion("donThuoc >=", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocLessThan(String value) {
            addCriterion("donThuoc <", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocLessThanOrEqualTo(String value) {
            addCriterion("donThuoc <=", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocLike(String value) {
            addCriterion("donThuoc like", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocNotLike(String value) {
            addCriterion("donThuoc not like", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocIn(List<String> values) {
            addCriterion("donThuoc in", values, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocNotIn(List<String> values) {
            addCriterion("donThuoc not in", values, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocBetween(String value1, String value2) {
            addCriterion("donThuoc between", value1, value2, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocNotBetween(String value1, String value2) {
            addCriterion("donThuoc not between", value1, value2, "donthuoc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.HoSo
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 13 22:58:16 ICT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.HoSo
     *
     * @mbg.generated Thu Jun 13 22:58:16 ICT 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}