package com.web.hospital.model;

import java.util.ArrayList;
import java.util.List;

public class MedicalVisitsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public MedicalVisitsExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdpIsNull() {
            addCriterion("idP is null");
            return (Criteria) this;
        }

        public Criteria andIdpIsNotNull() {
            addCriterion("idP is not null");
            return (Criteria) this;
        }

        public Criteria andIdpEqualTo(Integer value) {
            addCriterion("idP =", value, "idp");
            return (Criteria) this;
        }

        public Criteria andIdpNotEqualTo(Integer value) {
            addCriterion("idP <>", value, "idp");
            return (Criteria) this;
        }

        public Criteria andIdpGreaterThan(Integer value) {
            addCriterion("idP >", value, "idp");
            return (Criteria) this;
        }

        public Criteria andIdpGreaterThanOrEqualTo(Integer value) {
            addCriterion("idP >=", value, "idp");
            return (Criteria) this;
        }

        public Criteria andIdpLessThan(Integer value) {
            addCriterion("idP <", value, "idp");
            return (Criteria) this;
        }

        public Criteria andIdpLessThanOrEqualTo(Integer value) {
            addCriterion("idP <=", value, "idp");
            return (Criteria) this;
        }

        public Criteria andIdpIn(List<Integer> values) {
            addCriterion("idP in", values, "idp");
            return (Criteria) this;
        }

        public Criteria andIdpNotIn(List<Integer> values) {
            addCriterion("idP not in", values, "idp");
            return (Criteria) this;
        }

        public Criteria andIdpBetween(Integer value1, Integer value2) {
            addCriterion("idP between", value1, value2, "idp");
            return (Criteria) this;
        }

        public Criteria andIdpNotBetween(Integer value1, Integer value2) {
            addCriterion("idP not between", value1, value2, "idp");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanIsNull() {
            addCriterion("hotenbenhnhan is null");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanIsNotNull() {
            addCriterion("hotenbenhnhan is not null");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanEqualTo(String value) {
            addCriterion("hotenbenhnhan =", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanNotEqualTo(String value) {
            addCriterion("hotenbenhnhan <>", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanGreaterThan(String value) {
            addCriterion("hotenbenhnhan >", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanGreaterThanOrEqualTo(String value) {
            addCriterion("hotenbenhnhan >=", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanLessThan(String value) {
            addCriterion("hotenbenhnhan <", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanLessThanOrEqualTo(String value) {
            addCriterion("hotenbenhnhan <=", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanLike(String value) {
            addCriterion("hotenbenhnhan like", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanNotLike(String value) {
            addCriterion("hotenbenhnhan not like", value, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanIn(List<String> values) {
            addCriterion("hotenbenhnhan in", values, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanNotIn(List<String> values) {
            addCriterion("hotenbenhnhan not in", values, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanBetween(String value1, String value2) {
            addCriterion("hotenbenhnhan between", value1, value2, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andHotenbenhnhanNotBetween(String value1, String value2) {
            addCriterion("hotenbenhnhan not between", value1, value2, "hotenbenhnhan");
            return (Criteria) this;
        }

        public Criteria andNgaykhamIsNull() {
            addCriterion("ngayKham is null");
            return (Criteria) this;
        }

        public Criteria andNgaykhamIsNotNull() {
            addCriterion("ngayKham is not null");
            return (Criteria) this;
        }

        public Criteria andNgaykhamEqualTo(String value) {
            addCriterion("ngayKham =", value, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamNotEqualTo(String value) {
            addCriterion("ngayKham <>", value, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamGreaterThan(String value) {
            addCriterion("ngayKham >", value, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamGreaterThanOrEqualTo(String value) {
            addCriterion("ngayKham >=", value, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamLessThan(String value) {
            addCriterion("ngayKham <", value, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamLessThanOrEqualTo(String value) {
            addCriterion("ngayKham <=", value, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamLike(String value) {
            addCriterion("ngayKham like", value, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamNotLike(String value) {
            addCriterion("ngayKham not like", value, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamIn(List<String> values) {
            addCriterion("ngayKham in", values, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamNotIn(List<String> values) {
            addCriterion("ngayKham not in", values, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamBetween(String value1, String value2) {
            addCriterion("ngayKham between", value1, value2, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andNgaykhamNotBetween(String value1, String value2) {
            addCriterion("ngayKham not between", value1, value2, "ngaykham");
            return (Criteria) this;
        }

        public Criteria andLidokhamIsNull() {
            addCriterion("lidoKham is null");
            return (Criteria) this;
        }

        public Criteria andLidokhamIsNotNull() {
            addCriterion("lidoKham is not null");
            return (Criteria) this;
        }

        public Criteria andLidokhamEqualTo(String value) {
            addCriterion("lidoKham =", value, "lidokham");
            return (Criteria) this;
        }

        public Criteria andLidokhamNotEqualTo(String value) {
            addCriterion("lidoKham <>", value, "lidokham");
            return (Criteria) this;
        }

        public Criteria andLidokhamGreaterThan(String value) {
            addCriterion("lidoKham >", value, "lidokham");
            return (Criteria) this;
        }

        public Criteria andLidokhamGreaterThanOrEqualTo(String value) {
            addCriterion("lidoKham >=", value, "lidokham");
            return (Criteria) this;
        }

        public Criteria andLidokhamLessThan(String value) {
            addCriterion("lidoKham <", value, "lidokham");
            return (Criteria) this;
        }

        public Criteria andLidokhamLessThanOrEqualTo(String value) {
            addCriterion("lidoKham <=", value, "lidokham");
            return (Criteria) this;
        }

        public Criteria andLidokhamLike(String value) {
            addCriterion("lidoKham like", value, "lidokham");
            return (Criteria) this;
        }

        public Criteria andLidokhamNotLike(String value) {
            addCriterion("lidoKham not like", value, "lidokham");
            return (Criteria) this;
        }

        public Criteria andLidokhamIn(List<String> values) {
            addCriterion("lidoKham in", values, "lidokham");
            return (Criteria) this;
        }

        public Criteria andLidokhamNotIn(List<String> values) {
            addCriterion("lidoKham not in", values, "lidokham");
            return (Criteria) this;
        }

        public Criteria andLidokhamBetween(String value1, String value2) {
            addCriterion("lidoKham between", value1, value2, "lidokham");
            return (Criteria) this;
        }

        public Criteria andLidokhamNotBetween(String value1, String value2) {
            addCriterion("lidoKham not between", value1, value2, "lidokham");
            return (Criteria) this;
        }

        public Criteria andChuandoanIsNull() {
            addCriterion("chuanDoan is null");
            return (Criteria) this;
        }

        public Criteria andChuandoanIsNotNull() {
            addCriterion("chuanDoan is not null");
            return (Criteria) this;
        }

        public Criteria andChuandoanEqualTo(String value) {
            addCriterion("chuanDoan =", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanNotEqualTo(String value) {
            addCriterion("chuanDoan <>", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanGreaterThan(String value) {
            addCriterion("chuanDoan >", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanGreaterThanOrEqualTo(String value) {
            addCriterion("chuanDoan >=", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanLessThan(String value) {
            addCriterion("chuanDoan <", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanLessThanOrEqualTo(String value) {
            addCriterion("chuanDoan <=", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanLike(String value) {
            addCriterion("chuanDoan like", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanNotLike(String value) {
            addCriterion("chuanDoan not like", value, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanIn(List<String> values) {
            addCriterion("chuanDoan in", values, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanNotIn(List<String> values) {
            addCriterion("chuanDoan not in", values, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanBetween(String value1, String value2) {
            addCriterion("chuanDoan between", value1, value2, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andChuandoanNotBetween(String value1, String value2) {
            addCriterion("chuanDoan not between", value1, value2, "chuandoan");
            return (Criteria) this;
        }

        public Criteria andGhichucuabacsiIsNull() {
            addCriterion("ghichucuabacsi is null");
            return (Criteria) this;
        }

        public Criteria andGhichucuabacsiIsNotNull() {
            addCriterion("ghichucuabacsi is not null");
            return (Criteria) this;
        }

        public Criteria andGhichucuabacsiEqualTo(String value) {
            addCriterion("ghichucuabacsi =", value, "ghichucuabacsi");
            return (Criteria) this;
        }

        public Criteria andGhichucuabacsiNotEqualTo(String value) {
            addCriterion("ghichucuabacsi <>", value, "ghichucuabacsi");
            return (Criteria) this;
        }

        public Criteria andGhichucuabacsiGreaterThan(String value) {
            addCriterion("ghichucuabacsi >", value, "ghichucuabacsi");
            return (Criteria) this;
        }

        public Criteria andGhichucuabacsiGreaterThanOrEqualTo(String value) {
            addCriterion("ghichucuabacsi >=", value, "ghichucuabacsi");
            return (Criteria) this;
        }

        public Criteria andGhichucuabacsiLessThan(String value) {
            addCriterion("ghichucuabacsi <", value, "ghichucuabacsi");
            return (Criteria) this;
        }

        public Criteria andGhichucuabacsiLessThanOrEqualTo(String value) {
            addCriterion("ghichucuabacsi <=", value, "ghichucuabacsi");
            return (Criteria) this;
        }

        public Criteria andGhichucuabacsiLike(String value) {
            addCriterion("ghichucuabacsi like", value, "ghichucuabacsi");
            return (Criteria) this;
        }

        public Criteria andGhichucuabacsiNotLike(String value) {
            addCriterion("ghichucuabacsi not like", value, "ghichucuabacsi");
            return (Criteria) this;
        }

        public Criteria andGhichucuabacsiIn(List<String> values) {
            addCriterion("ghichucuabacsi in", values, "ghichucuabacsi");
            return (Criteria) this;
        }

        public Criteria andGhichucuabacsiNotIn(List<String> values) {
            addCriterion("ghichucuabacsi not in", values, "ghichucuabacsi");
            return (Criteria) this;
        }

        public Criteria andGhichucuabacsiBetween(String value1, String value2) {
            addCriterion("ghichucuabacsi between", value1, value2, "ghichucuabacsi");
            return (Criteria) this;
        }

        public Criteria andGhichucuabacsiNotBetween(String value1, String value2) {
            addCriterion("ghichucuabacsi not between", value1, value2, "ghichucuabacsi");
            return (Criteria) this;
        }

        public Criteria andDonthuocIsNull() {
            addCriterion("donthuoc is null");
            return (Criteria) this;
        }

        public Criteria andDonthuocIsNotNull() {
            addCriterion("donthuoc is not null");
            return (Criteria) this;
        }

        public Criteria andDonthuocEqualTo(String value) {
            addCriterion("donthuoc =", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocNotEqualTo(String value) {
            addCriterion("donthuoc <>", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocGreaterThan(String value) {
            addCriterion("donthuoc >", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocGreaterThanOrEqualTo(String value) {
            addCriterion("donthuoc >=", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocLessThan(String value) {
            addCriterion("donthuoc <", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocLessThanOrEqualTo(String value) {
            addCriterion("donthuoc <=", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocLike(String value) {
            addCriterion("donthuoc like", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocNotLike(String value) {
            addCriterion("donthuoc not like", value, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocIn(List<String> values) {
            addCriterion("donthuoc in", values, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocNotIn(List<String> values) {
            addCriterion("donthuoc not in", values, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocBetween(String value1, String value2) {
            addCriterion("donthuoc between", value1, value2, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andDonthuocNotBetween(String value1, String value2) {
            addCriterion("donthuoc not between", value1, value2, "donthuoc");
            return (Criteria) this;
        }

        public Criteria andIddIsNull() {
            addCriterion("idD is null");
            return (Criteria) this;
        }

        public Criteria andIddIsNotNull() {
            addCriterion("idD is not null");
            return (Criteria) this;
        }

        public Criteria andIddEqualTo(Integer value) {
            addCriterion("idD =", value, "idd");
            return (Criteria) this;
        }

        public Criteria andIddNotEqualTo(Integer value) {
            addCriterion("idD <>", value, "idd");
            return (Criteria) this;
        }

        public Criteria andIddGreaterThan(Integer value) {
            addCriterion("idD >", value, "idd");
            return (Criteria) this;
        }

        public Criteria andIddGreaterThanOrEqualTo(Integer value) {
            addCriterion("idD >=", value, "idd");
            return (Criteria) this;
        }

        public Criteria andIddLessThan(Integer value) {
            addCriterion("idD <", value, "idd");
            return (Criteria) this;
        }

        public Criteria andIddLessThanOrEqualTo(Integer value) {
            addCriterion("idD <=", value, "idd");
            return (Criteria) this;
        }

        public Criteria andIddIn(List<Integer> values) {
            addCriterion("idD in", values, "idd");
            return (Criteria) this;
        }

        public Criteria andIddNotIn(List<Integer> values) {
            addCriterion("idD not in", values, "idd");
            return (Criteria) this;
        }

        public Criteria andIddBetween(Integer value1, Integer value2) {
            addCriterion("idD between", value1, value2, "idd");
            return (Criteria) this;
        }

        public Criteria andIddNotBetween(Integer value1, Integer value2) {
            addCriterion("idD not between", value1, value2, "idd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated do_not_delete_during_merge Tue May 14 15:47:45 ICT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}