package com.web.hospital.model;

public class MedicalVisits {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MedicalVisits.ID
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MedicalVisits.idP
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    private Integer idp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MedicalVisits.hotenbenhnhan
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    private String hotenbenhnhan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MedicalVisits.ngayKham
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    private String ngaykham;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MedicalVisits.lidoKham
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    private String lidokham;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MedicalVisits.chuanDoan
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    private String chuandoan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MedicalVisits.ghichucuabacsi
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    private String ghichucuabacsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MedicalVisits.donthuoc
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    private String donthuoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MedicalVisits.idD
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    private Integer idd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MedicalVisits.ID
     *
     * @return the value of dbo.MedicalVisits.ID
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MedicalVisits.ID
     *
     * @param id the value for dbo.MedicalVisits.ID
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MedicalVisits.idP
     *
     * @return the value of dbo.MedicalVisits.idP
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public Integer getIdp() {
        return idp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MedicalVisits.idP
     *
     * @param idp the value for dbo.MedicalVisits.idP
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public void setIdp(Integer idp) {
        this.idp = idp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MedicalVisits.hotenbenhnhan
     *
     * @return the value of dbo.MedicalVisits.hotenbenhnhan
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public String getHotenbenhnhan() {
        return hotenbenhnhan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MedicalVisits.hotenbenhnhan
     *
     * @param hotenbenhnhan the value for dbo.MedicalVisits.hotenbenhnhan
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public void setHotenbenhnhan(String hotenbenhnhan) {
        this.hotenbenhnhan = hotenbenhnhan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MedicalVisits.ngayKham
     *
     * @return the value of dbo.MedicalVisits.ngayKham
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public String getNgaykham() {
        return ngaykham;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MedicalVisits.ngayKham
     *
     * @param ngaykham the value for dbo.MedicalVisits.ngayKham
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public void setNgaykham(String ngaykham) {
        this.ngaykham = ngaykham;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MedicalVisits.lidoKham
     *
     * @return the value of dbo.MedicalVisits.lidoKham
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public String getLidokham() {
        return lidokham;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MedicalVisits.lidoKham
     *
     * @param lidokham the value for dbo.MedicalVisits.lidoKham
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public void setLidokham(String lidokham) {
        this.lidokham = lidokham;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MedicalVisits.chuanDoan
     *
     * @return the value of dbo.MedicalVisits.chuanDoan
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public String getChuandoan() {
        return chuandoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MedicalVisits.chuanDoan
     *
     * @param chuandoan the value for dbo.MedicalVisits.chuanDoan
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public void setChuandoan(String chuandoan) {
        this.chuandoan = chuandoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MedicalVisits.ghichucuabacsi
     *
     * @return the value of dbo.MedicalVisits.ghichucuabacsi
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public String getGhichucuabacsi() {
        return ghichucuabacsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MedicalVisits.ghichucuabacsi
     *
     * @param ghichucuabacsi the value for dbo.MedicalVisits.ghichucuabacsi
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public void setGhichucuabacsi(String ghichucuabacsi) {
        this.ghichucuabacsi = ghichucuabacsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MedicalVisits.donthuoc
     *
     * @return the value of dbo.MedicalVisits.donthuoc
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public String getDonthuoc() {
        return donthuoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MedicalVisits.donthuoc
     *
     * @param donthuoc the value for dbo.MedicalVisits.donthuoc
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public void setDonthuoc(String donthuoc) {
        this.donthuoc = donthuoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MedicalVisits.idD
     *
     * @return the value of dbo.MedicalVisits.idD
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public Integer getIdd() {
        return idd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MedicalVisits.idD
     *
     * @param idd the value for dbo.MedicalVisits.idD
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    public void setIdd(Integer idd) {
        this.idd = idd;
    }
}