package com.web.hospital.model;

public class Patients {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Patients.idP
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    private Integer idp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Patients.hoTenBenhNhan
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    private String hotenbenhnhan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Patients.namSinh
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    private String namsinh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Patients.gioiTinh
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    private String gioitinh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Patients.SDT
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    private String sdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Patients.diaChi
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    private String diachi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Patients.email
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Patients.role
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Patients.idD
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    private Integer idd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Patients.benh
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    private String benh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Patients.idP
     *
     * @return the value of dbo.Patients.idP
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public Integer getIdp() {
        return idp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Patients.idP
     *
     * @param idp the value for dbo.Patients.idP
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public void setIdp(Integer idp) {
        this.idp = idp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Patients.hoTenBenhNhan
     *
     * @return the value of dbo.Patients.hoTenBenhNhan
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public String getHotenbenhnhan() {
        return hotenbenhnhan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Patients.hoTenBenhNhan
     *
     * @param hotenbenhnhan the value for dbo.Patients.hoTenBenhNhan
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public void setHotenbenhnhan(String hotenbenhnhan) {
        this.hotenbenhnhan = hotenbenhnhan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Patients.namSinh
     *
     * @return the value of dbo.Patients.namSinh
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public String getNamsinh() {
        return namsinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Patients.namSinh
     *
     * @param namsinh the value for dbo.Patients.namSinh
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public void setNamsinh(String namsinh) {
        this.namsinh = namsinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Patients.gioiTinh
     *
     * @return the value of dbo.Patients.gioiTinh
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public String getGioitinh() {
        return gioitinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Patients.gioiTinh
     *
     * @param gioitinh the value for dbo.Patients.gioiTinh
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Patients.SDT
     *
     * @return the value of dbo.Patients.SDT
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public String getSdt() {
        return sdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Patients.SDT
     *
     * @param sdt the value for dbo.Patients.SDT
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Patients.diaChi
     *
     * @return the value of dbo.Patients.diaChi
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public String getDiachi() {
        return diachi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Patients.diaChi
     *
     * @param diachi the value for dbo.Patients.diaChi
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Patients.email
     *
     * @return the value of dbo.Patients.email
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Patients.email
     *
     * @param email the value for dbo.Patients.email
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Patients.role
     *
     * @return the value of dbo.Patients.role
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Patients.role
     *
     * @param role the value for dbo.Patients.role
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Patients.idD
     *
     * @return the value of dbo.Patients.idD
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public Integer getIdd() {
        return idd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Patients.idD
     *
     * @param idd the value for dbo.Patients.idD
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public void setIdd(Integer idd) {
        this.idd = idd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Patients.benh
     *
     * @return the value of dbo.Patients.benh
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public String getBenh() {
        return benh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Patients.benh
     *
     * @param benh the value for dbo.Patients.benh
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    public void setBenh(String benh) {
        this.benh = benh;
    }
}