package com.web.hospital.model;

import java.util.ArrayList;
import java.util.List;

public class phongkhamExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public phongkhamExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTenPhongKhamIsNull() {
            addCriterion("ten_phong_kham is null");
            return (Criteria) this;
        }

        public Criteria andTenPhongKhamIsNotNull() {
            addCriterion("ten_phong_kham is not null");
            return (Criteria) this;
        }

        public Criteria andTenPhongKhamEqualTo(String value) {
            addCriterion("ten_phong_kham =", value, "tenPhongKham");
            return (Criteria) this;
        }

        public Criteria andTenPhongKhamNotEqualTo(String value) {
            addCriterion("ten_phong_kham <>", value, "tenPhongKham");
            return (Criteria) this;
        }

        public Criteria andTenPhongKhamGreaterThan(String value) {
            addCriterion("ten_phong_kham >", value, "tenPhongKham");
            return (Criteria) this;
        }

        public Criteria andTenPhongKhamGreaterThanOrEqualTo(String value) {
            addCriterion("ten_phong_kham >=", value, "tenPhongKham");
            return (Criteria) this;
        }

        public Criteria andTenPhongKhamLessThan(String value) {
            addCriterion("ten_phong_kham <", value, "tenPhongKham");
            return (Criteria) this;
        }

        public Criteria andTenPhongKhamLessThanOrEqualTo(String value) {
            addCriterion("ten_phong_kham <=", value, "tenPhongKham");
            return (Criteria) this;
        }

        public Criteria andTenPhongKhamLike(String value) {
            addCriterion("ten_phong_kham like", value, "tenPhongKham");
            return (Criteria) this;
        }

        public Criteria andTenPhongKhamNotLike(String value) {
            addCriterion("ten_phong_kham not like", value, "tenPhongKham");
            return (Criteria) this;
        }

        public Criteria andTenPhongKhamIn(List<String> values) {
            addCriterion("ten_phong_kham in", values, "tenPhongKham");
            return (Criteria) this;
        }

        public Criteria andTenPhongKhamNotIn(List<String> values) {
            addCriterion("ten_phong_kham not in", values, "tenPhongKham");
            return (Criteria) this;
        }

        public Criteria andTenPhongKhamBetween(String value1, String value2) {
            addCriterion("ten_phong_kham between", value1, value2, "tenPhongKham");
            return (Criteria) this;
        }

        public Criteria andTenPhongKhamNotBetween(String value1, String value2) {
            addCriterion("ten_phong_kham not between", value1, value2, "tenPhongKham");
            return (Criteria) this;
        }

        public Criteria andDiaChiIsNull() {
            addCriterion("dia_chi is null");
            return (Criteria) this;
        }

        public Criteria andDiaChiIsNotNull() {
            addCriterion("dia_chi is not null");
            return (Criteria) this;
        }

        public Criteria andDiaChiEqualTo(String value) {
            addCriterion("dia_chi =", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiNotEqualTo(String value) {
            addCriterion("dia_chi <>", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiGreaterThan(String value) {
            addCriterion("dia_chi >", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiGreaterThanOrEqualTo(String value) {
            addCriterion("dia_chi >=", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiLessThan(String value) {
            addCriterion("dia_chi <", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiLessThanOrEqualTo(String value) {
            addCriterion("dia_chi <=", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiLike(String value) {
            addCriterion("dia_chi like", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiNotLike(String value) {
            addCriterion("dia_chi not like", value, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiIn(List<String> values) {
            addCriterion("dia_chi in", values, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiNotIn(List<String> values) {
            addCriterion("dia_chi not in", values, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiBetween(String value1, String value2) {
            addCriterion("dia_chi between", value1, value2, "diaChi");
            return (Criteria) this;
        }

        public Criteria andDiaChiNotBetween(String value1, String value2) {
            addCriterion("dia_chi not between", value1, value2, "diaChi");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiIsNull() {
            addCriterion("so_dien_thoai is null");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiIsNotNull() {
            addCriterion("so_dien_thoai is not null");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiEqualTo(String value) {
            addCriterion("so_dien_thoai =", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiNotEqualTo(String value) {
            addCriterion("so_dien_thoai <>", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiGreaterThan(String value) {
            addCriterion("so_dien_thoai >", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiGreaterThanOrEqualTo(String value) {
            addCriterion("so_dien_thoai >=", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiLessThan(String value) {
            addCriterion("so_dien_thoai <", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiLessThanOrEqualTo(String value) {
            addCriterion("so_dien_thoai <=", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiLike(String value) {
            addCriterion("so_dien_thoai like", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiNotLike(String value) {
            addCriterion("so_dien_thoai not like", value, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiIn(List<String> values) {
            addCriterion("so_dien_thoai in", values, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiNotIn(List<String> values) {
            addCriterion("so_dien_thoai not in", values, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiBetween(String value1, String value2) {
            addCriterion("so_dien_thoai between", value1, value2, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andSoDienThoaiNotBetween(String value1, String value2) {
            addCriterion("so_dien_thoai not between", value1, value2, "soDienThoai");
            return (Criteria) this;
        }

        public Criteria andGhiChuIsNull() {
            addCriterion("ghi_chu is null");
            return (Criteria) this;
        }

        public Criteria andGhiChuIsNotNull() {
            addCriterion("ghi_chu is not null");
            return (Criteria) this;
        }

        public Criteria andGhiChuEqualTo(String value) {
            addCriterion("ghi_chu =", value, "ghiChu");
            return (Criteria) this;
        }

        public Criteria andGhiChuNotEqualTo(String value) {
            addCriterion("ghi_chu <>", value, "ghiChu");
            return (Criteria) this;
        }

        public Criteria andGhiChuGreaterThan(String value) {
            addCriterion("ghi_chu >", value, "ghiChu");
            return (Criteria) this;
        }

        public Criteria andGhiChuGreaterThanOrEqualTo(String value) {
            addCriterion("ghi_chu >=", value, "ghiChu");
            return (Criteria) this;
        }

        public Criteria andGhiChuLessThan(String value) {
            addCriterion("ghi_chu <", value, "ghiChu");
            return (Criteria) this;
        }

        public Criteria andGhiChuLessThanOrEqualTo(String value) {
            addCriterion("ghi_chu <=", value, "ghiChu");
            return (Criteria) this;
        }

        public Criteria andGhiChuLike(String value) {
            addCriterion("ghi_chu like", value, "ghiChu");
            return (Criteria) this;
        }

        public Criteria andGhiChuNotLike(String value) {
            addCriterion("ghi_chu not like", value, "ghiChu");
            return (Criteria) this;
        }

        public Criteria andGhiChuIn(List<String> values) {
            addCriterion("ghi_chu in", values, "ghiChu");
            return (Criteria) this;
        }

        public Criteria andGhiChuNotIn(List<String> values) {
            addCriterion("ghi_chu not in", values, "ghiChu");
            return (Criteria) this;
        }

        public Criteria andGhiChuBetween(String value1, String value2) {
            addCriterion("ghi_chu between", value1, value2, "ghiChu");
            return (Criteria) this;
        }

        public Criteria andGhiChuNotBetween(String value1, String value2) {
            addCriterion("ghi_chu not between", value1, value2, "ghiChu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated do_not_delete_during_merge Sat May 18 01:34:07 ICT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}