package com.web.hospital.model;

public class phongkham {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.phong_kham.id
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.phong_kham.ten_phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    private String tenPhongKham;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.phong_kham.dia_chi
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    private String diaChi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.phong_kham.so_dien_thoai
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    private String soDienThoai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.phong_kham.ghi_chu
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    private String ghiChu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.phong_kham.id
     *
     * @return the value of dbo.phong_kham.id
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.phong_kham.id
     *
     * @param id the value for dbo.phong_kham.id
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.phong_kham.ten_phong_kham
     *
     * @return the value of dbo.phong_kham.ten_phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public String getTenPhongKham() {
        return tenPhongKham;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.phong_kham.ten_phong_kham
     *
     * @param tenPhongKham the value for dbo.phong_kham.ten_phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public void setTenPhongKham(String tenPhongKham) {
        this.tenPhongKham = tenPhongKham;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.phong_kham.dia_chi
     *
     * @return the value of dbo.phong_kham.dia_chi
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public String getDiaChi() {
        return diaChi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.phong_kham.dia_chi
     *
     * @param diaChi the value for dbo.phong_kham.dia_chi
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.phong_kham.so_dien_thoai
     *
     * @return the value of dbo.phong_kham.so_dien_thoai
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public String getSoDienThoai() {
        return soDienThoai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.phong_kham.so_dien_thoai
     *
     * @param soDienThoai the value for dbo.phong_kham.so_dien_thoai
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.phong_kham.ghi_chu
     *
     * @return the value of dbo.phong_kham.ghi_chu
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public String getGhiChu() {
        return ghiChu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.phong_kham.ghi_chu
     *
     * @param ghiChu the value for dbo.phong_kham.ghi_chu
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
}