package com.web.hospital.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class thongtincanhanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    public thongtincanhanExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdcanhanIsNull() {
            addCriterion("idcanhan is null");
            return (Criteria) this;
        }

        public Criteria andIdcanhanIsNotNull() {
            addCriterion("idcanhan is not null");
            return (Criteria) this;
        }

        public Criteria andIdcanhanEqualTo(Integer value) {
            addCriterion("idcanhan =", value, "idcanhan");
            return (Criteria) this;
        }

        public Criteria andIdcanhanNotEqualTo(Integer value) {
            addCriterion("idcanhan <>", value, "idcanhan");
            return (Criteria) this;
        }

        public Criteria andIdcanhanGreaterThan(Integer value) {
            addCriterion("idcanhan >", value, "idcanhan");
            return (Criteria) this;
        }

        public Criteria andIdcanhanGreaterThanOrEqualTo(Integer value) {
            addCriterion("idcanhan >=", value, "idcanhan");
            return (Criteria) this;
        }

        public Criteria andIdcanhanLessThan(Integer value) {
            addCriterion("idcanhan <", value, "idcanhan");
            return (Criteria) this;
        }

        public Criteria andIdcanhanLessThanOrEqualTo(Integer value) {
            addCriterion("idcanhan <=", value, "idcanhan");
            return (Criteria) this;
        }

        public Criteria andIdcanhanIn(List<Integer> values) {
            addCriterion("idcanhan in", values, "idcanhan");
            return (Criteria) this;
        }

        public Criteria andIdcanhanNotIn(List<Integer> values) {
            addCriterion("idcanhan not in", values, "idcanhan");
            return (Criteria) this;
        }

        public Criteria andIdcanhanBetween(Integer value1, Integer value2) {
            addCriterion("idcanhan between", value1, value2, "idcanhan");
            return (Criteria) this;
        }

        public Criteria andIdcanhanNotBetween(Integer value1, Integer value2) {
            addCriterion("idcanhan not between", value1, value2, "idcanhan");
            return (Criteria) this;
        }

        public Criteria andHotenIsNull() {
            addCriterion("hoten is null");
            return (Criteria) this;
        }

        public Criteria andHotenIsNotNull() {
            addCriterion("hoten is not null");
            return (Criteria) this;
        }

        public Criteria andHotenEqualTo(String value) {
            addCriterion("hoten =", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenNotEqualTo(String value) {
            addCriterion("hoten <>", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenGreaterThan(String value) {
            addCriterion("hoten >", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenGreaterThanOrEqualTo(String value) {
            addCriterion("hoten >=", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenLessThan(String value) {
            addCriterion("hoten <", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenLessThanOrEqualTo(String value) {
            addCriterion("hoten <=", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenLike(String value) {
            addCriterion("hoten like", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenNotLike(String value) {
            addCriterion("hoten not like", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenIn(List<String> values) {
            addCriterion("hoten in", values, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenNotIn(List<String> values) {
            addCriterion("hoten not in", values, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenBetween(String value1, String value2) {
            addCriterion("hoten between", value1, value2, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenNotBetween(String value1, String value2) {
            addCriterion("hoten not between", value1, value2, "hoten");
            return (Criteria) this;
        }

        public Criteria andGioitinhIsNull() {
            addCriterion("gioiTinh is null");
            return (Criteria) this;
        }

        public Criteria andGioitinhIsNotNull() {
            addCriterion("gioiTinh is not null");
            return (Criteria) this;
        }

        public Criteria andGioitinhEqualTo(String value) {
            addCriterion("gioiTinh =", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhNotEqualTo(String value) {
            addCriterion("gioiTinh <>", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhGreaterThan(String value) {
            addCriterion("gioiTinh >", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhGreaterThanOrEqualTo(String value) {
            addCriterion("gioiTinh >=", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhLessThan(String value) {
            addCriterion("gioiTinh <", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhLessThanOrEqualTo(String value) {
            addCriterion("gioiTinh <=", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhLike(String value) {
            addCriterion("gioiTinh like", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhNotLike(String value) {
            addCriterion("gioiTinh not like", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhIn(List<String> values) {
            addCriterion("gioiTinh in", values, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhNotIn(List<String> values) {
            addCriterion("gioiTinh not in", values, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhBetween(String value1, String value2) {
            addCriterion("gioiTinh between", value1, value2, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhNotBetween(String value1, String value2) {
            addCriterion("gioiTinh not between", value1, value2, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andSdtIsNull() {
            addCriterion("SDT is null");
            return (Criteria) this;
        }

        public Criteria andSdtIsNotNull() {
            addCriterion("SDT is not null");
            return (Criteria) this;
        }

        public Criteria andSdtEqualTo(String value) {
            addCriterion("SDT =", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtNotEqualTo(String value) {
            addCriterion("SDT <>", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtGreaterThan(String value) {
            addCriterion("SDT >", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtGreaterThanOrEqualTo(String value) {
            addCriterion("SDT >=", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtLessThan(String value) {
            addCriterion("SDT <", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtLessThanOrEqualTo(String value) {
            addCriterion("SDT <=", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtLike(String value) {
            addCriterion("SDT like", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtNotLike(String value) {
            addCriterion("SDT not like", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtIn(List<String> values) {
            addCriterion("SDT in", values, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtNotIn(List<String> values) {
            addCriterion("SDT not in", values, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtBetween(String value1, String value2) {
            addCriterion("SDT between", value1, value2, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtNotBetween(String value1, String value2) {
            addCriterion("SDT not between", value1, value2, "sdt");
            return (Criteria) this;
        }

        public Criteria andNgaysinhIsNull() {
            addCriterion("ngaysinh is null");
            return (Criteria) this;
        }

        public Criteria andNgaysinhIsNotNull() {
            addCriterion("ngaysinh is not null");
            return (Criteria) this;
        }

        public Criteria andNgaysinhEqualTo(Date value) {
            addCriterionForJDBCDate("ngaysinh =", value, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhNotEqualTo(Date value) {
            addCriterionForJDBCDate("ngaysinh <>", value, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhGreaterThan(Date value) {
            addCriterionForJDBCDate("ngaysinh >", value, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ngaysinh >=", value, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhLessThan(Date value) {
            addCriterionForJDBCDate("ngaysinh <", value, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ngaysinh <=", value, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhIn(List<Date> values) {
            addCriterionForJDBCDate("ngaysinh in", values, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhNotIn(List<Date> values) {
            addCriterionForJDBCDate("ngaysinh not in", values, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ngaysinh between", value1, value2, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ngaysinh not between", value1, value2, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andDiachiIsNull() {
            addCriterion("diaChi is null");
            return (Criteria) this;
        }

        public Criteria andDiachiIsNotNull() {
            addCriterion("diaChi is not null");
            return (Criteria) this;
        }

        public Criteria andDiachiEqualTo(String value) {
            addCriterion("diaChi =", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotEqualTo(String value) {
            addCriterion("diaChi <>", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiGreaterThan(String value) {
            addCriterion("diaChi >", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiGreaterThanOrEqualTo(String value) {
            addCriterion("diaChi >=", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiLessThan(String value) {
            addCriterion("diaChi <", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiLessThanOrEqualTo(String value) {
            addCriterion("diaChi <=", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiLike(String value) {
            addCriterion("diaChi like", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotLike(String value) {
            addCriterion("diaChi not like", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiIn(List<String> values) {
            addCriterion("diaChi in", values, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotIn(List<String> values) {
            addCriterion("diaChi not in", values, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiBetween(String value1, String value2) {
            addCriterion("diaChi between", value1, value2, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotBetween(String value1, String value2) {
            addCriterion("diaChi not between", value1, value2, "diachi");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 14 08:59:46 ICT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}