package com.web.hospital.mapper.dbo;

import com.web.hospital.model.doctor;
import com.web.hospital.model.doctorExample;
import com.web.hospital.model.khoa;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface doctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Doctor
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    long countByExample(doctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Doctor
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    int deleteByExample(doctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Doctor
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    int insert(doctor row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Doctor
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    int insertSelective(doctor row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Doctor
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    List<doctor> selectByExample(doctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Doctor
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    int updateByExampleSelective(@Param("row") doctor row, @Param("example") doctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Doctor
     *
     * @mbg.generated Wed May 08 19:13:59 ICT 2024
     */
    int updateByExample(@Param("row") doctor row, @Param("example") doctorExample example);
    List<doctor> getdoctor();
    doctor getdoctorbyID(@Param("idd") int idd);
    doctor searchbyName(@Param("hotenbacsi") String hotenbacsi);
    doctor getiddByusername(@Param("username") String username);
    doctor findbyidd(@Param("idd") int idd);
    int updatedoc(@Param("hotenbacsi") String hotenbacsi,@Param("namsinh") String namsinh,@Param("gioitinh") String gioitinh,
    		@Param("sdt") String sdt,@Param("email") String email,@Param("username") String username,@Param("idd") int idd);
    int deletebyidd(@Param("idd") int idd);
    int adddoc(@Param("hotenbacsi") String hotenbacsi,@Param("namsinh") String namsinh,@Param("gioitinh") String gioitinh,
    		@Param("sdt") String sdt,@Param("email") String email,@Param("username") String username);
    List<doctor> getdoctorbymakhoa(@Param("makhoa") int makhoa);

    doctor findDoctorByUsername(@Param("username") String username);
}