package com.web.hospital.mapper.dbo;

import com.web.hospital.model.historygiaodich;
import com.web.hospital.model.historygiaodichExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface historygiaodichMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historygiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    long countByExample(historygiaodichExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historygiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    int deleteByExample(historygiaodichExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historygiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    int deleteByPrimaryKey(Integer idgiaodich);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historygiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    int insert(historygiaodich row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historygiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    int insertSelective(historygiaodich row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historygiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    List<historygiaodich> selectByExample(historygiaodichExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historygiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    historygiaodich selectByPrimaryKey(Integer idgiaodich);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historygiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    int updateByExampleSelective(@Param("row") historygiaodich row, @Param("example") historygiaodichExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historygiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    int updateByExample(@Param("row") historygiaodich row, @Param("example") historygiaodichExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historygiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    int updateByPrimaryKeySelective(historygiaodich row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historygiaodich
     *
     * @mbg.generated Sun Jun 16 00:56:30 ICT 2024
     */
    int updateByPrimaryKey(historygiaodich row);
    int insertgd(@Param("magiaodich") String magiaodich , @Param("ngaygiaodich") Date ngaygiaodich,
                 @Param("mount") int mount , @Param("id") int id );
    List<historygiaodich> getallbyID(@Param("id") Integer id);
    List<historygiaodich> getall();
    List<historygiaodich> getallbyHoten(@Param("hoten") String hoten);
    List<historygiaodich> sortNewDay();
    List<historygiaodich> sortLastDay();
}