package com.web.hospital.mapper.dbo;

import com.web.hospital.model.booking;
import com.web.hospital.model.historylichkham;
import com.web.hospital.model.historylichkhamExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface historylichkhamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historylichkham
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    long countByExample(historylichkhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historylichkham
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    int deleteByExample(historylichkhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historylichkham
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    int insert(historylichkham row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historylichkham
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    int insertSelective(historylichkham row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historylichkham
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    List<historylichkham> selectByExample(historylichkhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historylichkham
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    int updateByExampleSelective(@Param("row") historylichkham row, @Param("example") historylichkhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.historylichkham
     *
     * @mbg.generated Sat Jun 15 17:20:55 ICT 2024
     */
    int updateByExample(@Param("row") historylichkham row, @Param("example") historylichkhamExample example);
    List<historylichkham> checkHistoryByID(@Param("id") int id);
    int insertHistory(@Param("stt") int stt, @Param("trangthai") String trangthai);

}