package com.web.hospital.mapper.dbo;

import com.web.hospital.model.booking;
import com.web.hospital.model.khoa;
import com.web.hospital.model.khoaExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface khoaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Khoa
     *
     * @mbg.generated Wed May 08 19:21:48 ICT 2024
     */
    long countByExample(khoaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Khoa
     *
     * @mbg.generated Wed May 08 19:21:48 ICT 2024
     */
    int deleteByExample(khoaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Khoa
     *
     * @mbg.generated Wed May 08 19:21:48 ICT 2024
     */
    int deleteByPrimaryKey(Integer makhoa);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Khoa
     *
     * @mbg.generated Wed May 08 19:21:48 ICT 2024
     */
    int insert(khoa row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Khoa
     *
     * @mbg.generated Wed May 08 19:21:48 ICT 2024
     */
    int insertSelective(khoa row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Khoa
     *
     * @mbg.generated Wed May 08 19:21:48 ICT 2024
     */
    List<khoa> selectByExample(khoaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Khoa
     *
     * @mbg.generated Wed May 08 19:21:48 ICT 2024
     */
    khoa selectByPrimaryKey(Integer makhoa);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Khoa
     *
     * @mbg.generated Wed May 08 19:21:48 ICT 2024
     */
    int updateByExampleSelective(@Param("row") khoa row, @Param("example") khoaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Khoa
     *
     * @mbg.generated Wed May 08 19:21:48 ICT 2024
     */
    int updateByExample(@Param("row") khoa row, @Param("example") khoaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Khoa
     *
     * @mbg.generated Wed May 08 19:21:48 ICT 2024
     */
    int updateByPrimaryKeySelective(khoa row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Khoa
     *
     * @mbg.generated Wed May 08 19:21:48 ICT 2024
     */
    int updateByPrimaryKey(khoa row);
    
    List<khoa> getKhoa();
    khoa findbymaKhoa(@Param("makhoa") int makhoa);
    int updateKhoa(@Param("tenkhoa") String tenkhoa,@Param("truongkhoa") String truongkhoa,@Param("makhoa") int makhoa);
    int deletebymakhoa(@Param("makhoa") int makhoa);
    int addKhoa(@Param("tenkhoa") String tenkhoa,@Param("truongkhoa") String truongkhoa,@Param("makhoa") int makhoa);
}