package com.web.hospital.mapper.dbo;

import com.web.hospital.model.MedicalVisits;
import com.web.hospital.model.MedicalVisitsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MedicalVisitsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    long countByExample(MedicalVisitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    int deleteByExample(MedicalVisitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    int insert(MedicalVisits row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    int insertSelective(MedicalVisits row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    List<MedicalVisits> selectByExample(MedicalVisitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    MedicalVisits selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    int updateByExampleSelective(@Param("row") MedicalVisits row, @Param("example") MedicalVisitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    int updateByExample(@Param("row") MedicalVisits row, @Param("example") MedicalVisitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    int updateByPrimaryKeySelective(MedicalVisits row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.MedicalVisits
     *
     * @mbg.generated Tue May 14 15:47:45 ICT 2024
     */
    int updateByPrimaryKey(MedicalVisits row);
    List<MedicalVisits> gellAllbyIdd(@Param("idd") int idd);
    MedicalVisits findbyID(@Param("id") int id);
    int updateMedical(@Param("hotenbenhnhan") String hotenbenhnhan,@Param("ngaykham") String ngaykham,@Param("lidokham") String lidokham,
    		@Param("chuandoan") String chuandoan,@Param("ghichucuabacsi") String ghichucuabacsi,@Param("donthuoc") String donthuoc,@Param("id") int id);
    int deletebyID(@Param("id") int id);
    int addmedical(@Param("hotenbenhnhan") String hotenbenhnhan,@Param("ngaykham") String ngaykham,@Param("lidokham") String lidokham,
    		@Param("chuandoan") String chuandoan,@Param("ghichucuabacsi") String ghichucuabacsi,@Param("donthuoc") String donthuoc,@Param("idd") int idd);

}