package com.web.hospital.mapper.dbo;

import com.web.hospital.model.Patients;
import com.web.hospital.model.PatientsExample;
import com.web.hospital.model.booking;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PatientsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Patients
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    long countByExample(PatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Patients
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    int deleteByExample(PatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Patients
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    int insert(Patients row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Patients
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    int insertSelective(Patients row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Patients
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    List<Patients> selectByExample(PatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Patients
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Patients row, @Param("example") PatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Patients
     *
     * @mbg.generated Tue May 14 01:22:16 ICT 2024
     */
    int updateByExample(@Param("row") Patients row, @Param("example") PatientsExample example);
    List<Patients> listPatientsByidD(@Param("idd") int idd);
    Patients findbyidp(@Param("idp") int idp);
    int updateBenhNhan(@Param("hotenbenhnhan") String hotenbenhnhan,@Param("namsinh") String namsinh,@Param("gioitinh") String gioitinh,
    		@Param("sdt") String sdt,@Param("diachi") String diachi,@Param("email") String email,
    		@Param("benh") String benh,@Param("idp") int idp);
    int deletebyidp(@Param("idp") int idp);
    int addBenhNhan(@Param("hotenbenhnhan") String hotenbenhnhan,@Param("namsinh") String namsinh,@Param("gioitinh") String gioitinh,
    		@Param("sdt") String sdt,@Param("diachi") String diachi,@Param("email") String email,@Param("idd") int idd,@Param("benh") String benh);
}