package com.web.hospital.mapper.dbo;

import com.web.hospital.model.Account;
import com.web.hospital.model.phongkham;
import com.web.hospital.model.phongkhamExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface phongkhamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    long countByExample(phongkhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    int deleteByExample(phongkhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    int insert(phongkham row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    int insertSelective(phongkham row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    List<phongkham> selectByExample(phongkhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    phongkham selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    int updateByExampleSelective(@Param("row") phongkham row, @Param("example") phongkhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    int updateByExample(@Param("row") phongkham row, @Param("example") phongkhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    int updateByPrimaryKeySelective(phongkham row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.phong_kham
     *
     * @mbg.generated Sat May 18 01:34:07 ICT 2024
     */
    int updateByPrimaryKey(phongkham row);
    
    List<phongkham> selectallpk();
    	
    phongkham findbyidpk(@Param("id") int id);
    int updatepk(@Param("tenPhongKham") String tenPhongKham,@Param("diaChi") String diaChi,@Param("soDienThoai") String soDienThoai ,@Param("ghiChu") String ghiChu,@Param("id") int id);
    int deletebyidpk(@Param("id") int id);
    int addpk(@Param("tenPhongKham") String tenPhongKham,@Param("diaChi") String diaChi,@Param("soDienThoai") String soDienThoai ,@Param("ghiChu") String ghiChu);
}