package com.web.hospital.mapper.dbo;

import com.web.hospital.model.thongtincanhan;
import com.web.hospital.model.thongtincanhanExample;

import java.time.LocalDate;
import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface thongtincanhanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    long countByExample(thongtincanhanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    int deleteByExample(thongtincanhanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    int deleteByPrimaryKey(Integer idcanhan);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    int insert(thongtincanhan row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    int insertSelective(thongtincanhan row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    List<thongtincanhan> selectByExample(thongtincanhanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    thongtincanhan selectByPrimaryKey(Integer idcanhan);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    int updateByExampleSelective(@Param("row") thongtincanhan row, @Param("example") thongtincanhanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    int updateByExample(@Param("row") thongtincanhan row, @Param("example") thongtincanhanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    int updateByPrimaryKeySelective(thongtincanhan row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ThongTinCaNhan
     *
     * @mbg.generated Fri Jun 14 08:59:46 ICT 2024
     */
    int updateByPrimaryKey(thongtincanhan row);
    thongtincanhan getthongtincanhanByUsername(@Param("username") String username);
    int updataprofileByusername(@Param("hoten") String hoten, @Param("gioitinh") String gioitinh, @Param("sdt") String sdt,
                                @Param("ngaysinh") LocalDate ngaysinh, @Param("email") String email , @Param("diachi") String diachi ,
                                @Param("username") String username);
    int addusername(@Param("username") String username);
}